# Guide: https://docs.gitlab.com/ce/ci/yaml/README.html
# Only use spaces to indent your .yml configuration.
# -----

image: itential/argo:node8

# enable latest filesystem
variables:
  DOCKER_DRIVER: overlay2

# enable docker in docker
services:
- docker:dind

before_script:
  - node_setup

stages:
  - test

lint:
  stage: test
  script:
    - npm run lint

unit:
  stage: test
  script:
    - npm run test:unit

#security:
#  stage: test
#  allow_failure: true
#  script:
#    - npm audit --registry=https://registry.npmjs.org
